MODULE NRINT
	USE NRTYPE
	USE NRUTIL
	IMPLICIT NONE
	!-----------------------------------------------------------
 	CONTAINS
 	!-----------------------------------------------------------
	SUBROUTINE POLINT(XA,YA,X,Y,DY)
	IMPLICIT NONE
	REAL(SP), DIMENSION(:), INTENT(IN) :: XA,YA
	REAL(SP), INTENT(IN) :: X
	REAL(SP), INTENT(OUT) :: Y,DY
	!GIVEN ARRAYS XA AND YA OF LENGTH N , AND GIVEN A VALUE X, THIS ROUTINE RETURNS A VALUE Y,
	!AND AN ERROR ESTIMATE DY. IF P (X) IS THE POLYNOMIAL OF DEGREE N − 1 SUCH THAT P (XAI ) =
	!YAI , I = 1, . . . , N , THEN THE RETURNED VALUE Y = P (X).
	INTEGER(I4B) :: M,N,NS
	REAL(SP), DIMENSION(SIZE(XA)) :: C,D,DEN,HO
	N=ASSERT_EQ2(SIZE(XA),SIZE(YA),’POLINT’)
	D=YA
	C=YA
	HO=XA-X
	NS=IMINLOC(ABS(X-XA))			!FIND INDEX NS OF CLOSEST TABLE ENTRY.
	Y=YA(NS)						!THIS IS THE INITIAL APPROXIMATION TO Y.
	NS=NS-1
	DO M=1,N-1
	!FOR EACH COLUMN OF THE TABLEAU,
	!WE LOOP OVER THE CURRENT C’S AND D’S AND UP-
	!DATE THEM.
		DEN(1:N-M)=HO(1:N-M)-HO(1+M:N)
		IF (ANY(DEN(1:N-M) == 0.0)) CALL NRERROR(’POLINT: CALCULATION FAILURE’)
		!THIS ERROR CAN OCCUR ONLY IF TWO INPUT XA’S ARE (TO WITHIN ROUNDOFF) IDENTICAL.
		DEN(1:N-M)=(C(2:N-M+1)-D(1:N-M))/DEN(1:N-M)
		D(1:N-M)=HO(1+M:N)*DEN(1:N-M)
		C(1:N-M)=HO(1:N-M)*DEN(1:N-M)	!HERE THE C’S AND D’S ARE UPDATED.
		IF (2*NS < N-M) THEN
	!AFTER EACH COLUMN IN THE TABLEAU IS COMPLETED, WE DECIDE
	!WHICH CORRECTION, C OR D, WE WANT TO ADD TO OUR ACCU-
	!MULATING VALUE OF Y, I.E., WHICH PATH TO TAKE THROUGH
	!THE TABLEAU—FORKING UP OR DOWN. WE DO THIS IN SUCH A
	!WAY AS TO TAKE THE MOST “STRAIGHT LINE” ROUTE THROUGH THE
	!TABLEAU TO ITS APEX, UPDATING NS ACCORDINGLY TO KEEP TRACK
	!OF WHERE WE ARE. THIS ROUTE KEEPS THE PARTIAL APPROXIMA-
	!TIONS CENTERED (INSOFAR AS POSSIBLE) ON THE TARGET X. THE
	!LAST DY ADDED IS THUS THE ERROR INDICATION.
			DY=C(NS+1)
		ELSE
			DY=D(NS)
			NS=NS-1
		END IF
		Y=Y+DY
	END DO
	END SUBROUTINE POLINT
END MODULE NRINT