MODULE SPTYPE
 USE DOUBLE
 IMPLICIT NONE
 TYPE :: SPMAT
  INTEGER :: NELT = 0
  INTEGER, ALLOCATABLE, DIMENSION(:) :: ROW, COL
  COMPLEX(DP), ALLOCATABLE, DIMENSION(:) :: VAL
 END TYPE SPMAT
END MODULE SPTYPE

