PROGRAM TEST
 USE PE2D_TYPE
 USE PE2D_AUX
 USE PE2D_GROUND
 USE PE2D_ATMOS
 IMPLICIT NONE
 INTEGER(I4B) :: I, NROW, NCOL
 CHARACTER(LEN=100) :: FILENAME
 REAL(DP), DIMENSION(:,:), ALLOCATABLE :: S
 !REAL(DP), DIMENSION(:,:), ALLOCATABLE :: YP
 !REAL(DP), DIMENSION(:), ALLOCATABLE :: X, XA, YA
 !REAL(DP) :: L, DR
 !INTEGER(I4B) :: M, NDER
 FILENAME='alp_2d.dat'
 CALL STOREARRAY(FILENAME,S,NROW,NCOL)
 WRITE(*,*) "NLINES = ", NROW, "NCOLS = ", NCOL
 !L = 1.0_DP
 !N = 10
 !DR = L/N
 !ALLOCATE(XA(N), YA(N))
 !XA = (/ (DR*I, I=1,N) /)
 !YA = (/ (XA(I)**2, I=1,N) /)
 OPEN(UNIT=999,FILE='test.dat')
 DO I=1,NROW
  WRITE(999,100) S(I,1:NCOL)
 END DO
 100 FORMAT(2(F16.5,X))
 !--------
 !NDER = 2
 !M = 3000
 !L = XA(N)
 !M = 20
 !DR = L/M
 !ALLOCATE(X(M),YP(M,0:NDER))
 !X = (/ (DR*I, I=1,M) /)
 !YP = INTERP1(N,X,NDER,XA,YA)
 !OPEN(UNIT=998,FILE='test2.dat')
 !DO I=1,M
 ! WRITE(998,101) X(I), YP(I,:)  
 !END DO
 !101 FORMAT(4(F16.5,X))
 !--------
 !CALL GET_ENVIRONMENT_VARIABLE("nlines", FILENAME)
 !WRITE(*,*) TRIM(FILENAME)
END PROGRAM
