PROGRAM TEST
 USE PE2D_TYPE
 USE PE2D_AUX
 USE PE2D_GROUND
 USE PE2D_ATMOS
 IMPLICIT NONE
 INTEGER(I4B) :: I, NLINES, NCOLS
 CHARACTER(LEN=100) :: FILENAME
 REAL(DP), DIMENSION(:,:), ALLOCATABLE :: S
 REAL(DP), DIMENSION(:,:), ALLOCATABLE :: YP
 REAL(DP), DIMENSION(:), ALLOCATABLE :: X, XA, YA
 REAL(DP) :: L, DR
 INTEGER(I4B) :: M, NDER
 !--------
 !Data extraction
 FILENAME='../ground/alp_2d.dat'
 CALL READ_ARRAY(FILENAME,S,NLINES,NCOLS)
 OPEN(UNIT=999,FILE='../test/test_extract.dat')
 DO I=1,NROW
  WRITE(999,100) S(I,1:NCOL)
 END DO
 100 FORMAT(2(F16.5,X))
 !--------
 !Interpolation
 NDER = 2
 M = 3000
 L = XA(N)
 DR = L/M
 ALLOCATE(XA(NLINES),YA(NLINES))
 XA = S(1,:)
 YA = S(2,:)
 ALLOCATE(X(M),YP(M,0:NDER))
 X = (/ (DR*I, I=1,M) /)
 YP = POLINT1(N,X,NDER,XA,YA)
 OPEN(UNIT=998,FILE='../test/test_polint.dat')
 DO I=1,M
  WRITE(998,101) X(I), YP(I,:)  
 END DO
 101 FORMAT(4(F16.5,X))
 !--------
 !CALL GET_ENVIRONMENT_VARIABLE("nlines", FILENAME)
 !WRITE(*,*) TRIM(FILENAME)
END PROGRAM
