PROGRAM TEST
 USE 2DPE_AUX
 USE 2DPE_ATMOS
 IMPLICIT NONE
 INTEGER :: N, M, X
 CHARACTER(LEN=100) :: FILENAME
 REAL, DIMENSION(:,:), ALLOCATABLE :: X
 FILENAME='~/infratopo/Parabolic_Equation/2DPE/ground/alp_2d.dat'
 CALL STOREARRAY(FILENAME,X)
END PROGRAM
