PROGRAM TEST2
 USE PE2D_TYPE
 USE PE2D_AUX
 USE PE2D_GROUND
 USE PE2D_ATMOS
 IMPLICIT NONE
 INTEGER :: NLINES, NCOLS
 CHARACTER(LEN=100) :: FILENAME
 FILENAME = "read_data.dat"
 CALL DATA_SIZE(FILENAME,NLINES,NCOLS)
 WRITE(*,*) NLINES, " x ", NCOLS
END PROGRAM
