PROGRAM FOO
 USE MATLIB
 IMPLICIT NONE
 COMPLEX(DP), ALLOCATABLE, DIMENSION(:,:) :: X
 TYPE(SPMAT) :: SPX
 INTEGER :: I, J, N
 N = 3
 ALLOCATE(X(N,N))
 X = EYE(N)
 DO I = 1,N
  PRINT *, (/ (X(I,J), J = 1,N) /)
 END DO
 SPX = SPCONV(X)
 PRINT *, (/ (SPX%ROW(I), I = 1,SPX%NELT) /)
 PRINT *, (/ (SPX%COL(I), I = 1,SPX%NELT) /)
 PRINT *, (/ (SPX%VAL(I), I = 1,SPX%NELT) /)
END PROGRAM FOO
