MODULE SPARSETYPE

 TYPE SPARSE
 
  DOUBLE PRECISION, POINTER :: A(:)
  INTEGER, POINTER :: irow(:)
  INTEGER, POINTER :: jcol(:)
  INTEGER :: m, n
  INTEGER :: nnz
 END TYPE SPARSE
 
END MODULE SPARSETYPE
